# Welcome to Jekyll!

# Website settings
title: BR(BitReserve)
description: BitReserve (a.k.a BR) is a Singapore based Foundation registered.
keywords: BitReserve,BR
baseurl: /Test-BR
# url: http://www.coinusd.com
# url: http://127.0.0.1:4000
img_path: /static/assets/img/blog

# author
author:
  name: yangcongtou
  first_name: BR
  last_name: (BitReserve) 
  # cv: http://cv.jarrekk.com
  email: xiaohuan.liu@viewfin.com
  facebook_username: mvsofficial
  github_username: mvs-org
  linkedin_id: 13205915
  avatar: /static/assets/img/landing/RT-logo.png
  video: /static/assets/img/video/BitReserve2.mov
  skill_icon1:
    - name: icon-python
    - name: icon-shell
  skill_icon2:
    - name: icon-mongodb
    - name: icon-docker
  desc: I am a Full Stack engineer with website development, automation Ops and writing scripts experience. Life is a continuous learning process, so work makes me more rigorous, travel makes my life more colorful. I can make lots of friends when I coding and travel.

# comment
# disqus:
#   name: jalpc

# analytics
## google analytics
# ga:
#   id: UA-93473370-1xxxx

# go:
#   id: GTM-NHMS8GD



## growingIO
# gio:
  # id: a49d4901c7853da9

## donation
donation: off

# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge



  
# video 
gems:
  - octopress-video-tag
cdn: https://cdn.com